/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as CurrentAffairsRouteImport } from './routes/current-affairs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as StudyIndexRouteImport } from './routes/study.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as TestsTestIdRouteImport } from './routes/tests.$testId'
import { Route as StudyIdRouteImport } from './routes/study.$id'
import { Route as NewsIdRouteImport } from './routes/news.$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentAffairsRoute = CurrentAffairsRouteImport.update({
  id: '/current-affairs',
  path: '/current-affairs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsTestIdRoute = TestsTestIdRouteImport.update({
  id: '/tests/$testId',
  path: '/tests/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIdRoute = StudyIdRouteImport.update({
  id: '/study/$id',
  path: '/study/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/news/$id': typeof NewsIdRoute
  '/study/$id': typeof StudyIdRoute
  '/tests/$testId': typeof TestsTestIdRoute
  '/news/': typeof NewsIndexRoute
  '/study/': typeof StudyIndexRoute
  '/tests/': typeof TestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/news/$id': typeof NewsIdRoute
  '/study/$id': typeof StudyIdRoute
  '/tests/$testId': typeof TestsTestIdRoute
  '/news': typeof NewsIndexRoute
  '/study': typeof StudyIndexRoute
  '/tests': typeof TestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/news/$id': typeof NewsIdRoute
  '/study/$id': typeof StudyIdRoute
  '/tests/$testId': typeof TestsTestIdRoute
  '/news/': typeof NewsIndexRoute
  '/study/': typeof StudyIndexRoute
  '/tests/': typeof TestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/current-affairs'
    | '/notifications'
    | '/premium'
    | '/profile'
    | '/news/$id'
    | '/study/$id'
    | '/tests/$testId'
    | '/news/'
    | '/study/'
    | '/tests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/current-affairs'
    | '/notifications'
    | '/premium'
    | '/profile'
    | '/news/$id'
    | '/study/$id'
    | '/tests/$testId'
    | '/news'
    | '/study'
    | '/tests'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/current-affairs'
    | '/notifications'
    | '/premium'
    | '/profile'
    | '/news/$id'
    | '/study/$id'
    | '/tests/$testId'
    | '/news/'
    | '/study/'
    | '/tests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CurrentAffairsRoute: typeof CurrentAffairsRoute
  NotificationsRoute: typeof NotificationsRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRoute
  NewsIdRoute: typeof NewsIdRoute
  StudyIdRoute: typeof StudyIdRoute
  TestsTestIdRoute: typeof TestsTestIdRoute
  NewsIndexRoute: typeof NewsIndexRoute
  StudyIndexRoute: typeof StudyIndexRoute
  TestsIndexRoute: typeof TestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-affairs': {
      id: '/current-affairs'
      path: '/current-affairs'
      fullPath: '/current-affairs'
      preLoaderRoute: typeof CurrentAffairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$testId': {
      id: '/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof TestsTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$id': {
      id: '/study/$id'
      path: '/study/$id'
      fullPath: '/study/$id'
      preLoaderRoute: typeof StudyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CurrentAffairsRoute: CurrentAffairsRoute,
  NotificationsRoute: NotificationsRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRoute,
  NewsIdRoute: NewsIdRoute,
  StudyIdRoute: StudyIdRoute,
  TestsTestIdRoute: TestsTestIdRoute,
  NewsIndexRoute: NewsIndexRoute,
  StudyIndexRoute: StudyIndexRoute,
  TestsIndexRoute: TestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
